packages:
  - apps/*
  - packages/*
  - tooling/*
  - internal/*

overrides:
  date-fns: ^3.3.1
  fast-xml-parser: ^5.3.5
  nodemailer: ^9.0.1

packageExtensions:
  "@hookform/resolvers":
    peerDependencies:
      zod: ">=3.0.0"
  react-virtual:
    peerDependencies:
      react: ">=16.6.3"
