import { env } from "cloudflare:workers"
import { createRoute } from "@hono/zod-openapi"
import { FetchError } from "@unprice/error"
import { UnPriceCustomerError } from "@unprice/services/customers"
import { completeStripeSignUp } from "@unprice/services/use-cases"
import { z } from "zod"
import { UnpriceApiError, openApiErrorResponses, toUnpriceApiError } from "~/errors"
import type { App } from "~/hono/app"
import * as HttpStatusCodes from "~/util/http-status-codes"

const tags = ["paymentProvider"]

export const route = createRoute({
  path: "/v1/paymentProvider/stripe/signUp/{sessionId}/{projectId}",
  // this endpoint is not public, so we hide it
  hide: env.NODE_ENV === "production",
  summary: "stripe sign up",
  description:
    "This endpoint is called by stripe after the customer has signed up. No webhook is needed.",
  method: "get",
  tags,
  request: {
    params: z.object({
      projectId: z.string().openapi({
        description: "The project id the customer is signing up for",
        example: "1234567890",
      }),
      sessionId: z.string().openapi({
        description: "The stripe session generated by the sign up process",
        example: "cs_live_a1b2c3d4e5f6g7h8i9j0",
      }),
    }),
  },
  responses: {
    ...openApiErrorResponses,
    [HttpStatusCodes.MOVED_TEMPORARILY]: {
      description: "Redirect",
      headers: {
        Location: {
          description: "URL to redirect to",
          schema: {
            type: "string",
            format: "uri",
          },
        },
      },
    },
  },
})

export type StripeSignUpRequest = z.infer<typeof route.request.params>

export const registerStripeSignUpV1 = (app: App) =>
  app.openapi(route, async (c) => {
    const { sessionId, projectId } = c.req.valid("param")
    const key = c.req.header("cf-connecting-ip") ?? c.req.header("x-forwarded-for") ?? projectId
    const { customer, subscription } = c.get("services")

    // rate limit the request
    const result = await c.env.RL_FREE_1000_60s.limit({ key })

    if (!result) {
      throw new UnpriceApiError({
        code: "RATE_LIMITED",
        message: "Rate limit exceeded, please don't DDos me :(",
      })
    }

    const { err, val } = await completeStripeSignUp(
      {
        services: {
          customers: customer,
          subscriptions: subscription,
        },
        db: c.get("db"),
        logger: c.get("logger"),
        analytics: c.get("analytics"),
        waitUntil: c.get("waitUntil"),
      },
      {
        projectId,
        sessionId,
      }
    )

    if (err) {
      if (err instanceof UnPriceCustomerError) {
        if (err.code === "CUSTOMER_SESSION_NOT_FOUND") {
          throw new UnpriceApiError({
            code: "NOT_FOUND",
            message: err.message,
          })
        }

        if (err.code === "CUSTOMER_EXTERNAL_ID_CONFLICT") {
          throw new UnpriceApiError({
            code: "CONFLICT",
            message: err.message,
          })
        }

        if (err.code === "PAYMENT_PROVIDER_ERROR") {
          throw new UnpriceApiError({
            code: "BAD_REQUEST",
            message: err.message,
          })
        }

        throw new UnpriceApiError({
          code: "INTERNAL_SERVER_ERROR",
          message: err.message,
        })
      }

      if (err instanceof FetchError) {
        throw new UnpriceApiError({
          code: "INTERNAL_SERVER_ERROR",
          message: err.message,
        })
      }

      throw toUnpriceApiError(err)
    }

    // in development wrangler do weird things with the url
    if (c.env.NODE_ENV === "development") {
      return c.html(`
        <html>
          <head><meta http-equiv="refresh" content="0;url=${val.redirectUrl}" /></head>
          <body>
            Redirecting from client side (only in development)...
          </body>
        </html>
      `)
    }

    // redirect to the success URL
    return c.redirect(val.redirectUrl, HttpStatusCodes.MOVED_TEMPORARILY)
  })
