import type { operations } from "@unprice/api"

type MonetizationConfig =
  operations["monetization.apply"]["requestBody"]["content"]["application/json"]["config"]

export const LOAD_TEST_PLAN_SLUG = "load-test-pro"
export const LOAD_TEST_EVENT_SLUGS = ["api_request", "tokens_generated"] as const
export const LOAD_TEST_FEATURE_SLUGS = ["agent-access", "api-requests", "output-tokens"] as const

export const loadTestPricing = {
  events: [
    {
      slug: "api_request",
      name: "API request",
      availableProperties: [],
    },
    {
      slug: "tokens_generated",
      name: "Tokens generated",
      availableProperties: ["output_tokens"],
    },
  ],
  features: [
    {
      slug: "agent-access",
      title: "Agent Access",
      description: "Access to the agent API",
      unitOfMeasure: "access",
    },
    {
      slug: "api-requests",
      title: "API Requests",
      description: "Agent API requests processed during the billing period",
      unitOfMeasure: "requests",
    },
    {
      slug: "output-tokens",
      title: "Output Tokens",
      description: "Tokens generated by agent workloads",
      unitOfMeasure: "tokens",
    },
  ],
  plans: [
    {
      slug: LOAD_TEST_PLAN_SLUG,
      title: "Load Test Pro",
      description: "Isolated production plan for performance and ingestion tests",
      defaultPlan: true,
      version: {
        currency: "USD",
        paymentProvider: "sandbox",
        paymentMethodRequired: false,
        billingConfig: {
          name: "monthly",
          interval: "month",
          intervalCount: 1,
        },
        features: [
          {
            featureSlug: "agent-access",
            featureType: "flat",
            config: { price: "49.00" },
          },
          {
            featureSlug: "api-requests",
            featureType: "usage",
            config: { usageMode: "unit", price: "0.001" },
            meterConfig: {
              eventSlug: "api_request",
              aggregationMethod: "count",
            },
            limit: 1_000_000,
            resetConfig: { interval: "month", intervalCount: 1 },
          },
          {
            featureSlug: "output-tokens",
            featureType: "usage",
            config: { usageMode: "unit", price: "0.00001" },
            meterConfig: {
              eventSlug: "tokens_generated",
              aggregationMethod: "sum",
              aggregationField: "output_tokens",
            },
            limit: 100_000_000,
            resetConfig: { interval: "month", intervalCount: 1 },
          },
        ],
      },
    },
  ],
} satisfies MonetizationConfig
