ALTER TABLE "unprice_entitlements" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "unprice_entitlements" CASCADE;--> statement-breakpoint
ALTER TABLE "unprice_apikeys" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_apikeys" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_apikeys" ALTER COLUMN "default_customer_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_account" ALTER COLUMN "userId" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_authenticator" ALTER COLUMN "userId" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_session" ALTER COLUMN "sessionToken" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_session" ALTER COLUMN "userId" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_user" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_verificationToken" ALTER COLUMN "identifier" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_verificationToken" ALTER COLUMN "token" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_customer_sessions" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_customers" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_customers" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_domains" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_domains" ALTER COLUMN "workspace_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_events" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_events" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_features" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_features" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_billing_periods" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_billing_periods" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_billing_periods" ALTER COLUMN "subscription_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_billing_periods" ALTER COLUMN "customer_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_billing_periods" ALTER COLUMN "subscription_phase_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_billing_periods" ALTER COLUMN "subscription_item_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_billing_periods" ALTER COLUMN "invoice_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_credit_grants" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_credit_grants" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_credit_grants" ALTER COLUMN "customer_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_invoice_credit_applications" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_invoice_credit_applications" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_invoice_credit_applications" ALTER COLUMN "invoice_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_invoice_credit_applications" ALTER COLUMN "credit_grant_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_invoice_items" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_invoice_items" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_invoice_items" ALTER COLUMN "invoice_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_invoice_items" ALTER COLUMN "billing_period_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_invoice_items" ALTER COLUMN "subscription_item_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_invoice_items" ALTER COLUMN "feature_plan_version_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_invoices" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_invoices" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_invoices" ALTER COLUMN "subscription_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_invoices" ALTER COLUMN "customer_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_ledger_entries" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_ledger_entries" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_ledger_entries" ALTER COLUMN "ledger_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_ledger_entries" ALTER COLUMN "customer_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_ledger_entries" ALTER COLUMN "subscription_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_ledger_entries" ALTER COLUMN "subscription_phase_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_ledger_entries" ALTER COLUMN "subscription_item_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_ledger_entries" ALTER COLUMN "billing_period_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_ledger_entries" ALTER COLUMN "feature_plan_version_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_ledgers" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_ledgers" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_ledgers" ALTER COLUMN "customer_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_pages" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_pages" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_payment_provider_config" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_payment_provider_config" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_plans" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_plans" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_plan_versions_features" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_plan_versions_features" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_plan_versions_features" ALTER COLUMN "plan_version_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_plan_versions_features" ALTER COLUMN "feature_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_plan_versions" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_plan_versions" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_plan_versions" ALTER COLUMN "plan_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_plan_versions" ALTER COLUMN "published_by" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_plan_versions" ALTER COLUMN "archived_by" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_customer_provider_ids" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_customer_provider_ids" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_customer_provider_ids" ALTER COLUMN "customer_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_webhook_events" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_webhook_events" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_projects" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_projects" ALTER COLUMN "workspace_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_subscription_items" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_subscription_items" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_subscription_items" ALTER COLUMN "feature_plan_version_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_subscription_items" ALTER COLUMN "subscription_phase_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_subscription_items" ALTER COLUMN "subscription_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_subscription_phases" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_subscription_phases" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_subscription_phases" ALTER COLUMN "subscription_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_subscription_phases" ALTER COLUMN "plan_version_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_subscriptions" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_subscriptions" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_subscriptions" ALTER COLUMN "customers_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_subscription_locks" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_subscription_locks" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_invites" ALTER COLUMN "workspace_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_invites" ALTER COLUMN "invited_by" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_members" ALTER COLUMN "workspace_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_members" ALTER COLUMN "user_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_workspaces" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_workspaces" ALTER COLUMN "created_by" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_grants" ALTER COLUMN "id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_grants" ALTER COLUMN "project_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_grants" ALTER COLUMN "feature_plan_version_id" SET DATA TYPE varchar(36) COLLATE "C";--> statement-breakpoint
ALTER TABLE "unprice_grants" ALTER COLUMN "subject_id" SET DATA TYPE varchar(36) COLLATE "C";